name: markdown-linting

on:

  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get changed files
        continue-on-error: true
        run: |
          echo "CHANGED_FILES=$(gh pr diff ${{ github.event.number }} --name-only | grep '\.md$' | xargs)" >> $GITHUB_ENV

      - name: Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: ${{ env.CHANGED_FILES}}
